apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vb4soq4h8-go
  janus-idp.io/tekton: vb4soq4h8-go
  backstage.io/kubernetes-id: vb4soq4h8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vb4soq4h8-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
